### ISSUE TITLE
Create new reINVITEs

### ISSUE THREAD

**Issue by soulatsos** [dbelias/myITSPProvider#2]
Please extend the reINVITE functionality:
-reINVITE without SDP
-reINVITE with a=inactive attribute

Thanks,
Tasos

**Comment by dbelias** [comment]
Re-Invite without SDP is implemented.
Re-Invite with a=inactive is also implemented. This is achieved through Hold feature.However, I am not sure if the content of SDP is correct. Perhaps the IP and port should be 0. Need to be investigated.
Hold and Re-Invite features are enhanced with new combo box in GUI.
The new version which supports these enhancements is V1.11.0

**Comment by dbelias** [comment]
Issue is closed
